[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"] 
  topics = ["iesl/wellhead/pressure", "iesl/wellhead/temperature", "iesl/wellhead/flow"]
  client_id = "telegraf_consumer"
  data_format = "json"
  json_time_key = "timestamp"
  json_time_format = "unix"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "iesl-super-token-2025"
  organization = "iesl"
  bucket = "wellhead_data"
